using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Code Quality",  "IDE0067:Dispose objects before losing scope")]
[assembly: SuppressMessage("Code Quality",  "IDE0068:Use recommended dispose pattern")]
[assembly: SuppressMessage("Design",        "CA1032:Implement standard exception constructors")]
[assembly: SuppressMessage("Design",        "CA1044:Properties should not be write only")]
[assembly: SuppressMessage("Design",        "CA1051:Do not declare visible instance fields")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters")]
[assembly: SuppressMessage("Naming",        "CA1707:Identifiers should not contain underscores")]
[assembly: SuppressMessage("Naming",        "CA1710:Identifiers should have correct suffix")]
[assembly: SuppressMessage("Naming",        "CA1720:Identifiers should not contain type names")]
[assembly: SuppressMessage("Performance",   "CA1819:Properties should not return arrays")]
[assembly: SuppressMessage("Style",         "IDE0016:Use 'throw' expression")]
[assembly: SuppressMessage("Style",         "IDE0054:Use compound assignment")]
[assembly: SuppressMessage("Style",         "IDE0059:Unnecessary assignment of a value")]
[assembly: SuppressMessage("Style",         "IDE0060:Remove unused parameter")]
[assembly: SuppressMessage("Style",         "IDE1006:Naming Styles")]
[assembly: SuppressMessage("Usage",         "CA2225:Operator overloads have named alternates")]

[assembly: SuppressMessage("Code Quality",  "IDE0051:Remove unused private members",        Justification = "<Pending>", Scope = "member", Target = "~M:Jannesen.FileFormat.Pdf.PdfDocumentWriter._writeTrailer14")]
[assembly: SuppressMessage("Code Quality",  "IDE0069:Disposable fields should be disposed", Justification = "<Pending>", Scope = "member", Target = "~F:Jannesen.FileFormat.Pdf.PdfContent._parent")]
[assembly: SuppressMessage("Reliability",   "CA2000:Dispose objects before losing scope",   Justification = "<Pending>", Scope = "member", Target = "~M:Jannesen.FileFormat.Pdf.PdfObjStmReader.#ctor(Jannesen.FileFormat.Pdf.PdfDocumentReader,Jannesen.FileFormat.Pdf.PdfObjectReader)")]
[assembly: SuppressMessage("Usage",         "CA2213:Disposable fields should be disposed",  Justification = "<Pending>", Scope = "member", Target = "~F:Jannesen.FileFormat.Pdf.PdfContent._parent")]

[assembly: SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "Not implemented in NET46")]